apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: pingpong
          image: artursk8straining.azurecr.io/pingpong301:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: DB_HOST
            value: "postgres-service"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "test"
            # valueFrom:
            #   secretKeyRef:
            #     name: postgres-secret
            #     key: POSTGRES_USER
          - name: DB_PASSWORD
            # value: "test"
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: DB_NAME
            # value: "testdatabase"
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_DB
          ports:
            - containerPort: 3000
