name: tag-trigger-action

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['tag-build-action']
    types: [completed]

jobs:
   trigger-workflow:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger Workflow in Target Repository
        env:
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/artur-S213/gitopsDeploy/actions/workflows/tag.yaml/dispatches \
          -d '{"event_type":"custom-event","client_payload":{"tag":"${{ github.ref }}"}}'

    